# root-app/templates/monitoring.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Cassius86/gitops-demo.git
    targetRevision: HEAD
    path: ./manifests/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true  # This option helps with CRD application
      - ApplyOutOfSyncOnly=true  # Only apply resources that are out of sync
      - Replace=false  # Don't replace resources