apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: solar-system-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Cassius86/gitops-demo.git
    targetRevision: HEAD
    path: ./app-of-apps/manifests/solar-system
  destination:
    server: https://kubernetes.default.svc
    namespace: solar-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true