# apps/monitoring/values/monitoring-values.yaml
grafana:
  adminPassword: admin
  persistence:
    enabled: false
  service:
    type: NodePort
    nodePort: 30300

prometheus:
  prometheusSpec:
    retention: 3d
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 3Gi
    service:
      type: NodePort
      nodePort: 30900