apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 4
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: solar-system
    spec:
      containers:
      - image: siddharth67/solar-system:v3
        name: solar-system
        resources: {}
status: {}

---
# service.yml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: solar-system
  name: solar-system-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: solar-system
  type: NodePort
status:
  loadBalancer: {}
